title: "Jacques Fattaccioli"
description: >-
  Researcher, educator and microfluidics enthusiast — this site shares projects, teaching and publications.
url: "https://mesobiolab.github.io"  # ← change USERNAME
baseurl: ""                        # for project site, set to "/REPO-NAME"
theme: minima

# SEO and sitemap
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5

# Navigation links (for the Minima header)
header_pages:
  - index.md
  - about.md

# Author info
author:
  name: Jacques Fattaccioli
  email: your.email@example.com

# Google Analytics (optional)
# google_analytics: G-XXXXXXX
