title: "MesoBioLab"
description: >-
  Homepage of the MesoBioLab team - Laboration Chimie Physique et Chimie du Vivant (UMR 8228)
  Département de Chimie, École Normale Supérieure, Paris
url: "https://mesobiolab.github.io"  # ← change USERNAME
baseurl: ""                        # for project site, set to "/REPO-NAME"
theme: minima

# SEO and sitemap
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5

# Navigation links (for the Minima header)
header_pages:
  - index.md
  - about.md

# Author info
author:
  name: Jacques Fattaccioli
  email: jacques.fattaccioli@ens.psl.eu

# Google Analytics (optional)
# google_analytics: G-XXXXXXX
